server:
 port: 8082
 tomcat:
  uri-encoding: UTF-8

#数据源与jpa配置
spring:
  datasource:
    url: jdbc:mysql://192.168.51.182:3306/tucow?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis:
 mapper-locations: classpath:mapper/*
 type-aliases-package: com.mgs.comment.dao