server:
  port: 8082

  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.51.182:3306/tucow?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat , wall , log4j

    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMills=5000


redis:
  host: localhost
  prot: 6379

mybatis:
  mapper-locations: classpath:mapper/*
  type-aliases-package: com.lkx.show.dao