#.yml - 提供了结构化及其嵌套的格式
#properties   server.port=8082
#ser.tomcat.url-encoding = utf-8
#如果的配置文件放在resources文件中，springboot会自动进行读取
server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8

#数据源与jpa配置
spring:
  datasource:
    url: jdbc:mysql://192.168.51.182:3306/tucow?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
##druid配置
#    type: com.alibaba.druid.pool.DruidDataSource
##配置监控统计拦截的filter，如果不写监控界面的Sql将无法进行统计。"wall"用于防火墙
#  filters: stat ,wall ,log4j
##connectProperties检测执行效率超过5000毫秒的Sql语句（检测慢Sql的记录）
#    connectProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMills=5000
  jpa:
    database: mysql
    show-sql: true   #显示sql语句
    hibernate:
        ddl-auto: update #使用hibernate来自动更新表结构，如果数据表不存在，则自动创建，若果修改了表结构，在程序启动时，则执行表解耦股的同步更新